version: "3.9"
services:
  app:
    container_name: ynot-corp
    build: .
    command: /bin/bash
    tty: true
    ports:
      - 3000:3000
    volumes:
      - node_modules:/app/node_modules
      - ./:/app:cached
volumes:
  node_modules: {}
